In [50]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk2-task3-aqi.ipynb")

# Task 3: Visualizing AQI during the 2017 Thomas Fire in Santa Barbara County

This task covers topics on the lesson on [time series](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-7-time-series.html). 

## Instructions 

- First, update the following cell to have a link to *your* Homework 2 GitHub repository:

**UPDATED LINK**

https://github.com/ssoriano22/eds220-hwk2.git


- Review the [complete rubric for this task](https://docs.google.com/document/d/1x0BoU6IH4cnOR1-n7i9CYQ9wUC37yDpYlQ4j6rCfcsU/edit?tab=t.0) before starting.

- **Make at least 5 commits. Generally, commit every time you finish a major step.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

- **Do not update the top cell with the `otter` import**, this is used internally for grading.


## About the data

In this task you will use [Air Quality Index (AQI)](https://www.airnow.gov/aqi/aqi-basics/) data from the [US Environmental Protection Agency](https://www.epa.gov) to visualize the impact on the AQI of the 2017 [Thomas Fire](https://en.wikipedia.org/wiki/Thomas_Fire) in Santa Barbara County.

## FINAL CODE

You will use the next code cell to complete the last exercise in the task. Leave it blank for now.

In [51]:
import pandas as pd

## 1

a. Read the [Air Quality Index (AQI) Basics](https://www.airnow.gov/aqi/aqi-basics/) from the AirNow.gov portal.

b. Go to [EPA's website on Air Quality Data Collected at Outdoor Monitors Across the US](https://www.epa.gov/outdoor-air-quality-data).

c. Under "Download Data", click on "Pre-generated Data Files".

d. Read the "About the data" section.

## 2
a. Back in the "Pre-generated Data Files" site, click on "Tables of Daily AQI".

b. Download the 2017 Daily AQI **by County** ZIP file `daily_aqi_by_county_2017.zip` and the 2018 Daily AQI **by County** ZIP file `daily_aqi_by_county_2018.zip`. Save both files in the same folder as this notebook.

We will be reading the data directly from the local ZIP files. Each ZIP file contains a single CSV that has been compressed to save space.

<!-- BEGIN QUESTION -->

c. In the next code cell read in the data from the local ZIP file using the [`pd.read_csv`] function with the `compression='zip'` parameter added and store it as `aqi_17`.

d. In the same cell, read in the data for the 2018 Daily AQI by County ZIP file and store it as `aqi_18`.

In [52]:
# Read in 2017 and 2018 data
aqi_17 = pd.read_csv('data/daily_aqi_by_county_2017.zip', compression='zip')
aqi_18 = pd.read_csv('data/daily_aqi_by_county_2018.zip', compression='zip')

<!-- END QUESTION -->

## 3
a. and b. Use the next two code cells to look at the head of both data frames. Store your results in `aqi_17_head` and `aqi_18_head`.

In [53]:
# a.
# Save first 5 rows of aqi_17
aqi_17_head = aqi_17.head()
aqi_17_head

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2017-01-01,28,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2017-01-04,29,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2017-01-10,25,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2017-01-13,40,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2017-01-16,22,Good,PM2.5,01-003-0010,1

In [54]:
# b.
# Save first 5 rows of aqi_18
aqi_18_head = aqi_18.head()
aqi_18_head

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2018-01-02,42,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2018-01-05,45,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2018-01-08,20,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2018-01-11,25,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2018-01-14,33,Good,PM2.5,01-003-0010,1

In [55]:
grader.check("q3_a")

q3_a results: All test cases passed!

<!-- BEGIN QUESTION -->

c. Use this code cell to make some other preliminary data exploration of your choosing.

In [56]:
# Check df dimensions (row, column)
print("AQI 2017 Dimensions (row, col):", aqi_17.shape)
print("AQI 2018 Dimensions (row, col):", aqi_18.shape)

# Check df column types and null values
print("AQI 2017 Column Info:")
aqi_17.info()
print("AQI 2018 Column Info:")
aqi_18.info()

# Check unique values in some object/string columns of this df
print("AQI 2017 State Name Unique Values:", aqi_17['State Name'].unique())
print("AQI 2018 State Name Unique Values:", aqi_18['State Name'].unique())
print("AQI 2017 Category Unique Values:", aqi_17['Category'].unique())
print("AQI 2018 Category Unique Values:", aqi_18['Category'].unique())

# Check range of AQI values (min-max)
print("AQI 2017 Min-Max AQI Values:", aqi_17['AQI'].min(),"-", aqi_17['AQI'].max())
print("AQI 2018 Min-Max AQI Values:", aqi_18['AQI'].min(),"-", aqi_18['AQI'].max())

AQI 2017 Dimensions (row, col): (326801, 10)
AQI 2018 Dimensions (row, col): (327541, 10)
AQI 2017 Column Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326801 entries, 0 to 326800
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State Name                 326801 non-null  object
 1   county Name                326801 non-null  object
 2   State Code                 326801 non-null  int64
 3   County Code                326801 non-null  int64
 4   Date                       326801 non-null  object
 5   AQI                        326801 non-null  int64
 6   Category                   326801 non-null  object
 7   Defining Parameter         326801 non-null  object
 8   Defining Site              326801 non-null  object
 9   Number of Sites Reporting  326801 non-null  int64
dtypes: int64(4), object(6)
memory usage: 24.9+ MB
AQI 2018 Column Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327541 entries, 0 to 327540
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State Name                 327541 non-null  object
 1   county Name                327541 non-null  object
 2   State Code                 327541 non-null  int64
 3   County Code                327541 non-null  int64
 4   Date                       327541 non-null  object
 5   AQI                        327541 non-null  int64
 6   Category                   327541 non-null  object
 7   Defining Parameter         327541 non-null  object
 8   Defining Site              327541 non-null  object
 9   Number of Sites Reporting  327541 non-null  int64
dtypes: int64(4), object(6)
memory usage: 25.0+ MB
AQI 2017 State Name Unique Values: ['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Country Of Mexico' 'Delaware' 'District Of Columbia'
 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia'
 'Wisconsin' 'Wyoming']
AQI 2018 State Name Unique Values: ['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Country Of Mexico' 'Delaware' 'District Of Columbia'
 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia'
 'Wisconsin' 'Wyoming']
AQI 2017 Category Unique Values: ['Good' 'Moderate' 'Unhealthy for Sensitive Groups' 'Unhealthy'
 'Very Unhealthy' 'Hazardous']
AQI 2018 Category Unique Values: ['Good' 'Moderate' 'Unhealthy' 'Unhealthy for Sensitive Groups'
 'Very Unhealthy' 'Hazardous']
AQI 2017 Min-Max AQI Values: 0 - 3767
AQI 2018 Min-Max AQI Values: 0 - 1051

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

d. Use this markdown cell to explain why you decided to do the exploration in c. and what information you obtained from doing it.

I looked at the dimensions (number of rows, columns) of each pandas.DataFrame to see the total number of rows and columns in each - the 2018 dataset has just under 1000 more rows than the 2017 dataset. I checked the column types and missing data (null) count for each dataset - both have the same 10 columns, and no null values in any column. I took a brief look at some of the object-type categories that I guessed would have a limited number of unique values - State Name and Category. The 2017 and 2018 datasets appear to have the exact same values for these columns. I also looked at the min and max Air Quality Index (AQI) values for each dataset - 2017 ranges from 0-3767, while 2018 ranges from 0-1051.

<!-- END QUESTION -->

## 4
We currently have two separate data frames. For this exercise we will need to "glue" them one on top of the other. The `pandas` function `pd.concat()` can achieve this. 

Pass `[aqi_17, aqi_18]` as the input of `pd.concat()` and store the output as `aqi`.  
In the next line run `aqi`.

NOTE: When we concatenate data frames like this, without any extra parameters for `pd.concat()` the indices for the two data frames are just "glued together", the index of the resulting data frame is not updated to start from 0. Notice the mismatch between the index of `aqi` and the number of rows in the complete data frame.

In [57]:
# Concatenate the 2017 and 2018 AQI dfs
aqi = pd.concat([aqi_17,aqi_18])
aqi

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2017-01-01,28,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2017-01-04,29,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2017-01-10,25,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2017-01-13,40,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2017-01-16,22,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...,...,...,...,...
327536,Wyoming,Weston,56,45,2018-12-27,36,Good,Ozone,56-045-0003,1
327537,Wyoming,Weston,56,45,2018-12-28,35,Good,Ozone,56-045-0003,1
327538,Wyoming,Weston,56,45,2018-12-29,35,Good,Ozone,56-045-0003,1
327539,Wyoming,Weston,56,45,2018-12-30,31,Good,Ozone,56-045-0003,1
327540,Wyoming,Weston,56,45,2018-12-31,35,Good,Ozone,56-045-0003,1

In [58]:
grader.check("q4")

q4 results: All test cases passed!

<!-- BEGIN QUESTION -->

## 5

Run the following code cell and use the next markdown cell to give a line by line explanation of the code below the comment "#Simplify column names". You might need to look up the `pandas` documentation.

In [59]:
# Initial column names: notice caps and spaces (difficult to work with!)
print(aqi.columns, '\n')

# Simplify column names
aqi.columns = (aqi.columns
                  .str.lower()
                  .str.replace(' ','_')
                )
print(aqi.columns, '\n')

Index(['State Name', 'county Name', 'State Code', 'County Code', 'Date', 'AQI',
       'Category', 'Defining Parameter', 'Defining Site',
       'Number of Sites Reporting'],
      dtype='object')

Index(['state_name', 'county_name', 'state_code', 'county_code', 'date', 'aqi',
       'category', 'defining_parameter', 'defining_site',
       'number_of_sites_reporting'],
      dtype='object')

The new column names are made - starting with the old columns `aqi.columns` - through the following steps. The `str.lower()` method changes all elements in aqi.columns to lowercase characters. The `str.replace(' ', '_')` method replaces every space character ' ' with a '_' character, for every element of the now lowercase aqi.columns. This final transformed result is saved to overwrite `aqi.columns`, which applies directly to the `aqi` pandas.DataFrame.

<!-- END QUESTION -->

## 6
In the next code cell:

a. Select only data from `Santa Barbara` county and store it in a new variable `aqi_sb`.

b. Remove the `state_name`, `county_name`, `state_code` and `county_code` columns from `aqi_sb`.

Your data frame should have the following columns in this order: `date`, `aqi`, `category`, `defining_parameter`, `defining_site`, `number_of_sites_reporting`.

In [60]:
# Select Santa Barbara county rows from aqi
aqi_sb = aqi[aqi['county_name'] == 'Santa Barbara']
# Remove the first 4 columns - county already selected
aqi_sb = aqi_sb.loc[:,'date':]
aqi_sb

,date,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
28648,2017-01-01,39,Good,Ozone,06-083-4003,12
28649,2017-01-02,39,Good,PM2.5,06-083-2011,11
28650,2017-01-03,71,Moderate,PM10,06-083-4003,12
28651,2017-01-04,34,Good,Ozone,06-083-4003,13
28652,2017-01-05,37,Good,Ozone,06-083-4003,12
...,...,...,...,...,...,...
29128,2018-12-27,37,Good,Ozone,06-083-1025,11
29129,2018-12-28,39,Good,Ozone,06-083-1021,12
29130,2018-12-29,39,Good,Ozone,06-083-1021,12
29131,2018-12-30,41,Good,PM2.5,06-083-1008,12
29132,2018-12-31,38,Good,Ozone,06-083-2004,12

In [61]:
grader.check("q6a")

q6a results: All test cases passed!

 
c. What is the data type of the `date` column? Write your answer in the markdown cell below.

The `date` column of the pandas.DataFrame `aqi_sb` is an object-type (string) column.

In [62]:
# Display column types
aqi_sb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 730 entries, 28648 to 29132
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       730 non-null    object
 1   aqi                        730 non-null    int64
 2   category                   730 non-null    object
 3   defining_parameter         730 non-null    object
 4   defining_site              730 non-null    object
 5   number_of_sites_reporting  730 non-null    int64
dtypes: int64(2), object(4)
memory usage: 39.9+ KB

<!-- BEGIN QUESTION -->

## 7
In the following cell:
1. Update the `date` column of `aqi_sb` to have the `datetime64` data type.
2. Update the index of `aqi_sb` to be the `date` column.

In [ ]:
# Update date column to datetime64
aqi_sb['date'] = pd.to_datetime(aqi_sb['date'])
# Set aqi_sb index to date column
aqi_sb = aqi_sb.set_index('date')
aqi_sb

,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
date,,,,,
2017-01-01,39,Good,Ozone,06-083-4003,12
2017-01-02,39,Good,PM2.5,06-083-2011,11
2017-01-03,71,Moderate,PM10,06-083-4003,12
2017-01-04,34,Good,Ozone,06-083-4003,13
2017-01-05,37,Good,Ozone,06-083-4003,12
...,...,...,...,...,...
2018-12-27,37,Good,Ozone,06-083-1025,11
2018-12-28,39,Good,Ozone,06-083-1021,12
2018-12-29,39,Good,Ozone,06-083-1021,12
2018-12-30,41,Good,PM2.5,06-083-1008,12
2018-12-31,38,Good,Ozone,06-083-2004,12

<!-- END QUESTION -->

## 8
In the next cell we will calculate an average over a [rolling window](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rolling.html) using the `rolling()` method for `pandas.Series`:

- `rolling()` is a lazy method, so we need to specify what we want to calculate over each window before it does something. 
- in this example we use the aggregator function `mean()` to calculate the average over each window
- the parameter '5D' indicates we want the window for our rolling average to be 5 days. 
- we get a `pandas.Series` as output

Store your answer in the `rolling_average` variable. Your result should be a `pandas.Series` indexed by `date`, with the 5-day averages as its values.

In [64]:
# Calculate AQI rolling average over 5 days
rolling_average = ...
rolling_average

Ellipsis

In [65]:
grader.check("q8")

q8 results:
    q8 - 1 result:
        ❌ Test case failed
        Trying:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Expecting nothing
        **********************************************************************
        Line 1, in q8 0
        Failed example:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Exception raised:
            Traceback (most recent call last):
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q8 0[0]>", line 1, in <module>
                pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/core/frame.py", line 890, in __init__
                raise ValueError("DataFrame constructor not properly called!")
            ValueError: DataFrame constructor not properly called!

## 9 

Without creating any new variables, add the mean of the AQI over a 5-day rolling window as a new column named `five_day_average` to the `aqi_sb` data frame.

In [66]:
aqi_sb

,date,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
28648,2017-01-01,39,Good,Ozone,06-083-4003,12
28649,2017-01-02,39,Good,PM2.5,06-083-2011,11
28650,2017-01-03,71,Moderate,PM10,06-083-4003,12
28651,2017-01-04,34,Good,Ozone,06-083-4003,13
28652,2017-01-05,37,Good,Ozone,06-083-4003,12
...,...,...,...,...,...,...
29128,2018-12-27,37,Good,Ozone,06-083-1025,11
29129,2018-12-28,39,Good,Ozone,06-083-1021,12
29130,2018-12-29,39,Good,Ozone,06-083-1021,12
29131,2018-12-30,41,Good,PM2.5,06-083-1008,12
29132,2018-12-31,38,Good,Ozone,06-083-2004,12

In [67]:
grader.check("q9")

q9 results:
    q9 - 1 result:
        ❌ Test case failed
        Trying:
            def test_q9(aqi_sb):
                try:
                    expected_data = pd.read_csv('data/t3_q9_df.csv', index_col='date', parse_dates=True)
                    pd.testing.assert_frame_equal(expected_data, aqi_sb)
                except AssertionError:
                    raise AssertionError('Incorrect answer.')
        Expecting nothing
        ok
        Trying:
            test_q9(aqi_sb)
        Expecting nothing
        **********************************************************************
        Line 7, in q9 0
        Failed example:
            test_q9(aqi_sb)
        Exception raised:
            Traceback (most recent call last):
              File "<doctest q9 0[0]>", line 4, in test_q9
                pd.testing.assert_frame_equal(expected_data, aqi_sb)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 1250, in assert_frame_equal
                assert_index_equal(
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 253, in assert_index_equal
                _check_types(left, right, obj=obj)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 235, in _check_types
                assert_class_equal(left, right, exact=exact, obj=obj)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 383, in assert_class_equal
                raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 620, in raise_assert_detail
                raise AssertionError(msg)
            AssertionError: DataFrame.index are different

            DataFrame.index classes are different
            [left]:  DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
                           '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
                           '2017-01-09', '2017-01-10',
                           ...
                           '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25',
                           '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29',
                           '2018-12-30', '2018-12-31'],
                          dtype='datetime64[ns]', name='date', length=730, freq=None)
            [right]: Index([28648, 28649, 28650, 28651, 28652, 28653, 28654, 28655, 28656, 28657,
                   ...
                   29123, 29124, 29125, 29126, 29127, 29128, 29129, 29130, 29131, 29132],
                  dtype='int64', length=730)

            During handling of the above exception, another exception occurred:

            Traceback (most recent call last):
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q9 0[1]>", line 1, in <module>
                test_q9(aqi_sb)
              File "<doctest q9 0[0]>", line 6, in test_q9
                raise AssertionError('Incorrect answer.')
            AssertionError: Incorrect answer.

<!-- BEGIN QUESTION -->

## 10
Make a line plot showing both the daily AQI and the 5-day average (5-day average on top of the AQI). Make necessary updates for the plot to be accurate, informative, and polished, even if simple. You're welcome to use plotting methods and packages beyond what we have covered in class! 

Can you see the AQI going up during the Thomas Fire in December 2017?

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [68]:
grader.check_all()

q3_a results: All test cases passed!

q4 results: All test cases passed!

q6a results: All test cases passed!

q8 results:
    q8 - 1 result:
        ❌ Test case failed
        Trying:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Expecting nothing
        **********************************************************************
        Line 1, in q8 0
        Failed example:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Exception raised:
            Traceback (most recent call last):
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q8 0[0]>", line 1, in <module>
                pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/core/frame.py", line 890, in __init__
                raise ValueError("DataFrame constructor not properly called!")
            ValueError: DataFrame constructor not properly called!

q9 results:
    q9 - 1 result:
        ❌ Test case failed
        Trying:
            def test_q9(aqi_sb):
                try:
                    expected_data = pd.read_csv('data/t3_q9_df.csv', index_col='date', parse_dates=True)
                    pd.testing.assert_frame_equal(expected_data, aqi_sb)
                except AssertionError:
                    raise AssertionError('Incorrect answer.')
        Expecting nothing
        ok
        Trying:
            test_q9(aqi_sb)
        Expecting nothing
        **********************************************************************
        Line 7, in q9 0
        Failed example:
            test_q9(aqi_sb)
        Exception raised:
            Traceback (most recent call last):
              File "<doctest q9 0[0]>", line 4, in test_q9
                pd.testing.assert_frame_equal(expected_data, aqi_sb)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 1250, in assert_frame_equal
                assert_index_equal(
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 253, in assert_index_equal
                _check_types(left, right, obj=obj)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 235, in _check_types
                assert_class_equal(left, right, exact=exact, obj=obj)
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 383, in assert_class_equal
                raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 620, in raise_assert_detail
                raise AssertionError(msg)
            AssertionError: DataFrame.index are different

            DataFrame.index classes are different
            [left]:  DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
                           '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
                           '2017-01-09', '2017-01-10',
                           ...
                           '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25',
                           '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29',
                           '2018-12-30', '2018-12-31'],
                          dtype='datetime64[ns]', name='date', length=730, freq=None)
            [right]: Index([28648, 28649, 28650, 28651, 28652, 28653, 28654, 28655, 28656, 28657,
                   ...
                   29123, 29124, 29125, 29126, 29127, 29128, 29129, 29130, 29131, 29132],
                  dtype='int64', length=730)

            During handling of the above exception, another exception occurred:

            Traceback (most recent call last):
              File "/Users/smsoriano/miniforge3/envs/eds220-env/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q9 0[1]>", line 1, in <module>
                test_q9(aqi_sb)
              File "<doctest q9 0[0]>", line 6, in test_q9
                raise AssertionError('Incorrect answer.')
            AssertionError: Incorrect answer.

<!-- END QUESTION -->

## 11


Collect all the relevant code into the first blank cell of the notebook titled "COMPLETE WORKFLOW". This single cell will have the end-to-end workflow: from importing libraries and loading the data, to producing the graph. The *only* output of this cell should be the graph you produced in the previous exercise. Further guidance on what to include in this final workflow is in the [assignment rubric](https://docs.google.com/document/d/1x0BoU6IH4cnOR1-n7i9CYQ9wUC37yDpYlQ4j6rCfcsU/edit?tab=t.0).